spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/stripe_service
    username: postgres
    password: Vignesh@123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    show-sql: true